spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hospital
    username: root
    password: peter12345
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000
      auto-commit: false
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false
        show_sql: true
        jdbc:
          batch_size: 50
          fetch_size: 50
          order_inserts: true
          order_updates: true
        generate_statistics: true
  application:
    name: hospital

server:
  port: 8081
